function A = dfdx(in1,in2)
%DFDX
%    A = DFDX(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    2024/02/26 18:04:45

u1 = in2(1,:);
A = reshape([u1.^2.*1.703e-7-3.0./5.0e+1,3.0./5.0e+1,1.0./2.5e+1,-3.0./5.0e+1],[2,2]);
end
