function h = output_equation(in1)
%OUTPUT_EQUATION
%    H = OUTPUT_EQUATION(IN1)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    2024/02/26 18:04:45

x2 = in1(2,:);
h = x2;
end
