function h = output_equation(in1)
%OUTPUT_EQUATION
%    H = OUTPUT_EQUATION(IN1)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    2024/03/29 16:09:40

x4 = in1(4,:);
h = x4;
end
