function f = state_equation(in1,in2)
%STATE_EQUATION
%    F = STATE_EQUATION(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    2024/02/27 05:21:42

u1 = in2(1,:);
u2 = in2(2,:);
u3 = in2(3,:);
u4 = in2(4,:);
u5 = in2(5,:);
x1 = in1(1,:);
x2 = in1(2,:);
x3 = in1(3,:);
x4 = in1(4,:);
t2 = u4./5.0e+1;
t3 = x4./2.5e+1;
t4 = x1.*(3.0./1.25e+2);
t5 = x2.*(3.0./1.25e+2);
t6 = x3.*(3.0./1.25e+2);
t7 = u5./1.2e+3;
mt1 = [t2+t3+t5+t6+t7-x1.*(2.7e+1./2.5e+2)+u1.^2.*(x1.*3.93e-3-1.717295e-1).*1.3e-4;t2+t3+t4+t6+t7-x2.*(2.7e+1./2.5e+2)+u2.^2.*(x2.*3.93e-3-1.717295e-1).*1.3e-4;t2+t3+t4+t5+t7-x3.*(2.7e+1./2.5e+2)+u3.^2.*(x3.*3.93e-3-1.717295e-1).*1.3e-4];
mt2 = [u5.*(3.0./8.0e+2)+x1./5.0e+1+x2./5.0e+1+x3./5.0e+1-x4.*(3.0./5.0e+1)];
f = [mt1;mt2];
end
