function out1 = state_equation_discrete(in1,in2)
%STATE_EQUATION_DISCRETE
%    OUT1 = STATE_EQUATION_DISCRETE(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    2024/02/26 18:04:45

u1 = in2(1,:);
u2 = in2(2,:);
u3 = in2(3,:);
x1 = in1(1,:);
x2 = in1(2,:);
out1 = [u2./5.0e+3+u3./1.2e+5+x1.*9.994e-1+x2./2.5e+3+u1.^2.*(x1.*3.93e-3-1.717295e-1).*4.333333333333333e-7;u3.*3.75e-5+x1.*6.0e-4+x2.*9.994e-1];
end
