function out1 = state_equation_discrete(in1,in2)
%STATE_EQUATION_DISCRETE
%    OUT1 = STATE_EQUATION_DISCRETE(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    2024/02/27 05:21:42

u1 = in2(1,:);
u2 = in2(2,:);
u3 = in2(3,:);
u4 = in2(4,:);
u5 = in2(5,:);
x1 = in1(1,:);
x2 = in1(2,:);
x3 = in1(3,:);
x4 = in1(4,:);
t2 = u4./5.0e+3;
t3 = x4./2.5e+3;
t4 = x1.*2.4e-4;
t5 = x2.*2.4e-4;
t6 = x3.*2.4e-4;
t7 = u5./1.2e+5;
mt1 = [t2+t3+t5+t6+t7+x1.*9.9892e-1+u1.^2.*(x1.*3.93e-3-1.717295e-1).*1.3e-6;t2+t3+t4+t6+t7+x2.*9.9892e-1+u2.^2.*(x2.*3.93e-3-1.717295e-1).*1.3e-6;t2+t3+t4+t5+t7+x3.*9.9892e-1+u3.^2.*(x3.*3.93e-3-1.717295e-1).*1.3e-6];
mt2 = [u5.*3.75e-5+x1./5.0e+3+x2./5.0e+3+x3./5.0e+3+x4.*9.994e-1];
out1 = [mt1;mt2];
end
