function f = state_equation(in1,in2)
%STATE_EQUATION
%    F = STATE_EQUATION(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    2024/02/26 07:02:31

u1 = in2(1,:);
u2 = in2(2,:);
u3 = in2(3,:);
x1 = in1(1,:);
x2 = in1(2,:);
t2 = x1.*(3.0./5.0e+1);
f = [-t2+u2./5.0e+1+u3./1.2e+3+x2./2.5e+1+u1.^2.*(x1.*3.93e-3-1.717295e-1).*4.333333333333333e-5;t2+u3.*(3.0./8.0e+2)-x2.*(3.0./5.0e+1)];
end
